url: http://FPGAwars.github.io
baseurl:

# Site settings
title: FPGAwars
email: fpgawars@gmail.com
description: Exploring the open side of the FPGAs

# Team names, titles and social links
people:

  - name: Juan González (Obijuan)
    social:
      - title: twitter
        url: https://twitter.com/obijuan_cube
      - title: google-plus
        url: https://plus.google.com/+JuanGonzalezGomez
      - title: github
        url: https://github.com/obijuan

  - name: Jesús Arroyo Torrens
    social:
      - title: twitter
        url: https://twitter.com/JesusArroyo89
      - title: google-plus
        url: https://plus.google.com/115177854757724458184
      - title: github
        url: https://github.com/Jesus89

  - name: Eladio Delgado
    social:
      - title: twitter
        url: https://twitter.com/EladioDM

# Build settings
markdown: kramdown
permalink: pretty

collections:
  - content
